// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "shift_line_buffer_array_ap_fixed_8u_config20_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic shift_line_buffer_array_ap_fixed_8u_config20_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic shift_line_buffer_array_ap_fixed_8u_config20_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> shift_line_buffer_array_ap_fixed_8u_config20_s::ap_ST_fsm_state1 = "1";
const sc_lv<32> shift_line_buffer_array_ap_fixed_8u_config20_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> shift_line_buffer_array_ap_fixed_8u_config20_s::ap_const_lv1_1 = "1";
const sc_lv<6> shift_line_buffer_array_ap_fixed_8u_config20_s::ap_const_lv6_21 = "100001";
const bool shift_line_buffer_array_ap_fixed_8u_config20_s::ap_const_boolean_1 = true;

shift_line_buffer_array_ap_fixed_8u_config20_s::shift_line_buffer_array_ap_fixed_8u_config20_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_buffer_Array_V_5_0_0_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_0_0_U");
    line_buffer_Array_V_5_0_0_U->clk(ap_clk);
    line_buffer_Array_V_5_0_0_U->reset(ap_rst);
    line_buffer_Array_V_5_0_0_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_0_0_U->ce0(line_buffer_Array_V_5_0_0_ce0);
    line_buffer_Array_V_5_0_0_U->we0(line_buffer_Array_V_5_0_0_we0);
    line_buffer_Array_V_5_0_0_U->d0(in_elem_data_0_V_read);
    line_buffer_Array_V_5_0_0_U->q0(line_buffer_Array_V_5_0_0_q0);
    line_buffer_Array_V_5_1_0_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_1_0_U");
    line_buffer_Array_V_5_1_0_U->clk(ap_clk);
    line_buffer_Array_V_5_1_0_U->reset(ap_rst);
    line_buffer_Array_V_5_1_0_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_1_0_U->ce0(line_buffer_Array_V_5_1_0_ce0);
    line_buffer_Array_V_5_1_0_U->we0(line_buffer_Array_V_5_1_0_we0);
    line_buffer_Array_V_5_1_0_U->d0(line_buffer_Array_V_5_0_0_q0);
    line_buffer_Array_V_5_1_0_U->q0(line_buffer_Array_V_5_1_0_q0);
    line_buffer_Array_V_5_0_1_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_0_1_U");
    line_buffer_Array_V_5_0_1_U->clk(ap_clk);
    line_buffer_Array_V_5_0_1_U->reset(ap_rst);
    line_buffer_Array_V_5_0_1_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_0_1_U->ce0(line_buffer_Array_V_5_0_1_ce0);
    line_buffer_Array_V_5_0_1_U->we0(line_buffer_Array_V_5_0_1_we0);
    line_buffer_Array_V_5_0_1_U->d0(in_elem_data_1_V_read);
    line_buffer_Array_V_5_0_1_U->q0(line_buffer_Array_V_5_0_1_q0);
    line_buffer_Array_V_5_1_1_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_1_1_U");
    line_buffer_Array_V_5_1_1_U->clk(ap_clk);
    line_buffer_Array_V_5_1_1_U->reset(ap_rst);
    line_buffer_Array_V_5_1_1_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_1_1_U->ce0(line_buffer_Array_V_5_1_1_ce0);
    line_buffer_Array_V_5_1_1_U->we0(line_buffer_Array_V_5_1_1_we0);
    line_buffer_Array_V_5_1_1_U->d0(line_buffer_Array_V_5_0_1_q0);
    line_buffer_Array_V_5_1_1_U->q0(line_buffer_Array_V_5_1_1_q0);
    line_buffer_Array_V_5_0_2_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_0_2_U");
    line_buffer_Array_V_5_0_2_U->clk(ap_clk);
    line_buffer_Array_V_5_0_2_U->reset(ap_rst);
    line_buffer_Array_V_5_0_2_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_0_2_U->ce0(line_buffer_Array_V_5_0_2_ce0);
    line_buffer_Array_V_5_0_2_U->we0(line_buffer_Array_V_5_0_2_we0);
    line_buffer_Array_V_5_0_2_U->d0(in_elem_data_2_V_read);
    line_buffer_Array_V_5_0_2_U->q0(line_buffer_Array_V_5_0_2_q0);
    line_buffer_Array_V_5_1_2_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_1_2_U");
    line_buffer_Array_V_5_1_2_U->clk(ap_clk);
    line_buffer_Array_V_5_1_2_U->reset(ap_rst);
    line_buffer_Array_V_5_1_2_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_1_2_U->ce0(line_buffer_Array_V_5_1_2_ce0);
    line_buffer_Array_V_5_1_2_U->we0(line_buffer_Array_V_5_1_2_we0);
    line_buffer_Array_V_5_1_2_U->d0(line_buffer_Array_V_5_0_2_q0);
    line_buffer_Array_V_5_1_2_U->q0(line_buffer_Array_V_5_1_2_q0);
    line_buffer_Array_V_5_0_3_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_0_3_U");
    line_buffer_Array_V_5_0_3_U->clk(ap_clk);
    line_buffer_Array_V_5_0_3_U->reset(ap_rst);
    line_buffer_Array_V_5_0_3_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_0_3_U->ce0(line_buffer_Array_V_5_0_3_ce0);
    line_buffer_Array_V_5_0_3_U->we0(line_buffer_Array_V_5_0_3_we0);
    line_buffer_Array_V_5_0_3_U->d0(in_elem_data_3_V_read);
    line_buffer_Array_V_5_0_3_U->q0(line_buffer_Array_V_5_0_3_q0);
    line_buffer_Array_V_5_1_3_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_1_3_U");
    line_buffer_Array_V_5_1_3_U->clk(ap_clk);
    line_buffer_Array_V_5_1_3_U->reset(ap_rst);
    line_buffer_Array_V_5_1_3_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_1_3_U->ce0(line_buffer_Array_V_5_1_3_ce0);
    line_buffer_Array_V_5_1_3_U->we0(line_buffer_Array_V_5_1_3_we0);
    line_buffer_Array_V_5_1_3_U->d0(line_buffer_Array_V_5_0_3_q0);
    line_buffer_Array_V_5_1_3_U->q0(line_buffer_Array_V_5_1_3_q0);
    line_buffer_Array_V_5_0_4_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_0_4_U");
    line_buffer_Array_V_5_0_4_U->clk(ap_clk);
    line_buffer_Array_V_5_0_4_U->reset(ap_rst);
    line_buffer_Array_V_5_0_4_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_0_4_U->ce0(line_buffer_Array_V_5_0_4_ce0);
    line_buffer_Array_V_5_0_4_U->we0(line_buffer_Array_V_5_0_4_we0);
    line_buffer_Array_V_5_0_4_U->d0(in_elem_data_4_V_read);
    line_buffer_Array_V_5_0_4_U->q0(line_buffer_Array_V_5_0_4_q0);
    line_buffer_Array_V_5_1_4_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_1_4_U");
    line_buffer_Array_V_5_1_4_U->clk(ap_clk);
    line_buffer_Array_V_5_1_4_U->reset(ap_rst);
    line_buffer_Array_V_5_1_4_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_1_4_U->ce0(line_buffer_Array_V_5_1_4_ce0);
    line_buffer_Array_V_5_1_4_U->we0(line_buffer_Array_V_5_1_4_we0);
    line_buffer_Array_V_5_1_4_U->d0(line_buffer_Array_V_5_0_4_q0);
    line_buffer_Array_V_5_1_4_U->q0(line_buffer_Array_V_5_1_4_q0);
    line_buffer_Array_V_5_0_5_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_0_5_U");
    line_buffer_Array_V_5_0_5_U->clk(ap_clk);
    line_buffer_Array_V_5_0_5_U->reset(ap_rst);
    line_buffer_Array_V_5_0_5_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_0_5_U->ce0(line_buffer_Array_V_5_0_5_ce0);
    line_buffer_Array_V_5_0_5_U->we0(line_buffer_Array_V_5_0_5_we0);
    line_buffer_Array_V_5_0_5_U->d0(in_elem_data_5_V_read);
    line_buffer_Array_V_5_0_5_U->q0(line_buffer_Array_V_5_0_5_q0);
    line_buffer_Array_V_5_1_5_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_1_5_U");
    line_buffer_Array_V_5_1_5_U->clk(ap_clk);
    line_buffer_Array_V_5_1_5_U->reset(ap_rst);
    line_buffer_Array_V_5_1_5_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_1_5_U->ce0(line_buffer_Array_V_5_1_5_ce0);
    line_buffer_Array_V_5_1_5_U->we0(line_buffer_Array_V_5_1_5_we0);
    line_buffer_Array_V_5_1_5_U->d0(line_buffer_Array_V_5_0_5_q0);
    line_buffer_Array_V_5_1_5_U->q0(line_buffer_Array_V_5_1_5_q0);
    line_buffer_Array_V_5_0_6_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_0_6_U");
    line_buffer_Array_V_5_0_6_U->clk(ap_clk);
    line_buffer_Array_V_5_0_6_U->reset(ap_rst);
    line_buffer_Array_V_5_0_6_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_0_6_U->ce0(line_buffer_Array_V_5_0_6_ce0);
    line_buffer_Array_V_5_0_6_U->we0(line_buffer_Array_V_5_0_6_we0);
    line_buffer_Array_V_5_0_6_U->d0(in_elem_data_6_V_read);
    line_buffer_Array_V_5_0_6_U->q0(line_buffer_Array_V_5_0_6_q0);
    line_buffer_Array_V_5_1_6_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_1_6_U");
    line_buffer_Array_V_5_1_6_U->clk(ap_clk);
    line_buffer_Array_V_5_1_6_U->reset(ap_rst);
    line_buffer_Array_V_5_1_6_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_1_6_U->ce0(line_buffer_Array_V_5_1_6_ce0);
    line_buffer_Array_V_5_1_6_U->we0(line_buffer_Array_V_5_1_6_we0);
    line_buffer_Array_V_5_1_6_U->d0(line_buffer_Array_V_5_0_6_q0);
    line_buffer_Array_V_5_1_6_U->q0(line_buffer_Array_V_5_1_6_q0);
    line_buffer_Array_V_5_0_7_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_0_7_U");
    line_buffer_Array_V_5_0_7_U->clk(ap_clk);
    line_buffer_Array_V_5_0_7_U->reset(ap_rst);
    line_buffer_Array_V_5_0_7_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_0_7_U->ce0(line_buffer_Array_V_5_0_7_ce0);
    line_buffer_Array_V_5_0_7_U->we0(line_buffer_Array_V_5_0_7_we0);
    line_buffer_Array_V_5_0_7_U->d0(in_elem_data_7_V_read);
    line_buffer_Array_V_5_0_7_U->q0(line_buffer_Array_V_5_0_7_q0);
    line_buffer_Array_V_5_1_7_U = new shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb("line_buffer_Array_V_5_1_7_U");
    line_buffer_Array_V_5_1_7_U->clk(ap_clk);
    line_buffer_Array_V_5_1_7_U->reset(ap_rst);
    line_buffer_Array_V_5_1_7_U->address0(ap_var_for_const0);
    line_buffer_Array_V_5_1_7_U->ce0(line_buffer_Array_V_5_1_7_ce0);
    line_buffer_Array_V_5_1_7_U->we0(line_buffer_Array_V_5_1_7_we0);
    line_buffer_Array_V_5_1_7_U->d0(line_buffer_Array_V_5_0_7_q0);
    line_buffer_Array_V_5_1_7_U->q0(line_buffer_Array_V_5_1_7_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_8_V_read );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_9_V_read );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_34_V_read );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_35_V_read );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_36_V_read );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_37_V_read );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_38_V_read );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_39_V_read );

    SC_METHOD(thread_ap_return_16);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_56_V_read );

    SC_METHOD(thread_ap_return_17);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_57_V_read );

    SC_METHOD(thread_ap_return_18);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_58_V_read );

    SC_METHOD(thread_ap_return_19);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_59_V_read );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_10_V_read );

    SC_METHOD(thread_ap_return_20);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_60_V_read );

    SC_METHOD(thread_ap_return_21);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_61_V_read );

    SC_METHOD(thread_ap_return_22);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_62_V_read );

    SC_METHOD(thread_ap_return_23);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_63_V_read );

    SC_METHOD(thread_ap_return_24);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_16_V_read );

    SC_METHOD(thread_ap_return_25);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_17_V_read );

    SC_METHOD(thread_ap_return_26);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_18_V_read );

    SC_METHOD(thread_ap_return_27);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_19_V_read );

    SC_METHOD(thread_ap_return_28);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_20_V_read );

    SC_METHOD(thread_ap_return_29);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_21_V_read );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_11_V_read );

    SC_METHOD(thread_ap_return_30);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_22_V_read );

    SC_METHOD(thread_ap_return_31);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_23_V_read );

    SC_METHOD(thread_ap_return_32);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_1_0_q0 );

    SC_METHOD(thread_ap_return_33);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_1_1_q0 );

    SC_METHOD(thread_ap_return_34);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_1_2_q0 );

    SC_METHOD(thread_ap_return_35);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_1_3_q0 );

    SC_METHOD(thread_ap_return_36);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_1_4_q0 );

    SC_METHOD(thread_ap_return_37);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_1_5_q0 );

    SC_METHOD(thread_ap_return_38);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_1_6_q0 );

    SC_METHOD(thread_ap_return_39);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_1_7_q0 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_12_V_read );

    SC_METHOD(thread_ap_return_40);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_40_V_read );

    SC_METHOD(thread_ap_return_41);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_41_V_read );

    SC_METHOD(thread_ap_return_42);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_42_V_read );

    SC_METHOD(thread_ap_return_43);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_43_V_read );

    SC_METHOD(thread_ap_return_44);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_44_V_read );

    SC_METHOD(thread_ap_return_45);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_45_V_read );

    SC_METHOD(thread_ap_return_46);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_46_V_read );

    SC_METHOD(thread_ap_return_47);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_47_V_read );

    SC_METHOD(thread_ap_return_48);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_0_0_q0 );

    SC_METHOD(thread_ap_return_49);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_0_1_q0 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_13_V_read );

    SC_METHOD(thread_ap_return_50);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_0_2_q0 );

    SC_METHOD(thread_ap_return_51);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_0_3_q0 );

    SC_METHOD(thread_ap_return_52);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_0_4_q0 );

    SC_METHOD(thread_ap_return_53);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_0_5_q0 );

    SC_METHOD(thread_ap_return_54);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_0_6_q0 );

    SC_METHOD(thread_ap_return_55);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_5_0_7_q0 );

    SC_METHOD(thread_ap_return_56);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_64_V_read );

    SC_METHOD(thread_ap_return_57);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_65_V_read );

    SC_METHOD(thread_ap_return_58);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_66_V_read );

    SC_METHOD(thread_ap_return_59);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_67_V_read );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_14_V_read );

    SC_METHOD(thread_ap_return_60);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_68_V_read );

    SC_METHOD(thread_ap_return_61);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_69_V_read );

    SC_METHOD(thread_ap_return_62);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_70_V_read );

    SC_METHOD(thread_ap_return_63);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_71_V_read );

    SC_METHOD(thread_ap_return_64);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_0_V_read );

    SC_METHOD(thread_ap_return_65);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_1_V_read );

    SC_METHOD(thread_ap_return_66);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_2_V_read );

    SC_METHOD(thread_ap_return_67);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_3_V_read );

    SC_METHOD(thread_ap_return_68);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_4_V_read );

    SC_METHOD(thread_ap_return_69);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_5_V_read );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_15_V_read );

    SC_METHOD(thread_ap_return_70);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_6_V_read );

    SC_METHOD(thread_ap_return_71);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_7_V_read );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_32_V_read );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_33_V_read );

    SC_METHOD(thread_line_buffer_Array_V_5_0_0_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_0_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_1_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_2_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_2_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_3_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_3_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_4_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_4_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_5_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_5_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_6_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_6_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_7_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_0_7_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_0_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_0_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_1_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_2_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_2_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_3_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_3_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_4_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_4_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_5_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_5_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_6_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_6_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_7_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_line_buffer_Array_V_5_1_7_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "shift_line_buffer_array_ap_fixed_8u_config20_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_elem_data_0_V_read, "(port)in_elem_data_0_V_read");
    sc_trace(mVcdFile, in_elem_data_1_V_read, "(port)in_elem_data_1_V_read");
    sc_trace(mVcdFile, in_elem_data_2_V_read, "(port)in_elem_data_2_V_read");
    sc_trace(mVcdFile, in_elem_data_3_V_read, "(port)in_elem_data_3_V_read");
    sc_trace(mVcdFile, in_elem_data_4_V_read, "(port)in_elem_data_4_V_read");
    sc_trace(mVcdFile, in_elem_data_5_V_read, "(port)in_elem_data_5_V_read");
    sc_trace(mVcdFile, in_elem_data_6_V_read, "(port)in_elem_data_6_V_read");
    sc_trace(mVcdFile, in_elem_data_7_V_read, "(port)in_elem_data_7_V_read");
    sc_trace(mVcdFile, kernel_window_8_V_read, "(port)kernel_window_8_V_read");
    sc_trace(mVcdFile, kernel_window_9_V_read, "(port)kernel_window_9_V_read");
    sc_trace(mVcdFile, kernel_window_10_V_read, "(port)kernel_window_10_V_read");
    sc_trace(mVcdFile, kernel_window_11_V_read, "(port)kernel_window_11_V_read");
    sc_trace(mVcdFile, kernel_window_12_V_read, "(port)kernel_window_12_V_read");
    sc_trace(mVcdFile, kernel_window_13_V_read, "(port)kernel_window_13_V_read");
    sc_trace(mVcdFile, kernel_window_14_V_read, "(port)kernel_window_14_V_read");
    sc_trace(mVcdFile, kernel_window_15_V_read, "(port)kernel_window_15_V_read");
    sc_trace(mVcdFile, kernel_window_16_V_read, "(port)kernel_window_16_V_read");
    sc_trace(mVcdFile, kernel_window_17_V_read, "(port)kernel_window_17_V_read");
    sc_trace(mVcdFile, kernel_window_18_V_read, "(port)kernel_window_18_V_read");
    sc_trace(mVcdFile, kernel_window_19_V_read, "(port)kernel_window_19_V_read");
    sc_trace(mVcdFile, kernel_window_20_V_read, "(port)kernel_window_20_V_read");
    sc_trace(mVcdFile, kernel_window_21_V_read, "(port)kernel_window_21_V_read");
    sc_trace(mVcdFile, kernel_window_22_V_read, "(port)kernel_window_22_V_read");
    sc_trace(mVcdFile, kernel_window_23_V_read, "(port)kernel_window_23_V_read");
    sc_trace(mVcdFile, kernel_window_32_V_read, "(port)kernel_window_32_V_read");
    sc_trace(mVcdFile, kernel_window_33_V_read, "(port)kernel_window_33_V_read");
    sc_trace(mVcdFile, kernel_window_34_V_read, "(port)kernel_window_34_V_read");
    sc_trace(mVcdFile, kernel_window_35_V_read, "(port)kernel_window_35_V_read");
    sc_trace(mVcdFile, kernel_window_36_V_read, "(port)kernel_window_36_V_read");
    sc_trace(mVcdFile, kernel_window_37_V_read, "(port)kernel_window_37_V_read");
    sc_trace(mVcdFile, kernel_window_38_V_read, "(port)kernel_window_38_V_read");
    sc_trace(mVcdFile, kernel_window_39_V_read, "(port)kernel_window_39_V_read");
    sc_trace(mVcdFile, kernel_window_40_V_read, "(port)kernel_window_40_V_read");
    sc_trace(mVcdFile, kernel_window_41_V_read, "(port)kernel_window_41_V_read");
    sc_trace(mVcdFile, kernel_window_42_V_read, "(port)kernel_window_42_V_read");
    sc_trace(mVcdFile, kernel_window_43_V_read, "(port)kernel_window_43_V_read");
    sc_trace(mVcdFile, kernel_window_44_V_read, "(port)kernel_window_44_V_read");
    sc_trace(mVcdFile, kernel_window_45_V_read, "(port)kernel_window_45_V_read");
    sc_trace(mVcdFile, kernel_window_46_V_read, "(port)kernel_window_46_V_read");
    sc_trace(mVcdFile, kernel_window_47_V_read, "(port)kernel_window_47_V_read");
    sc_trace(mVcdFile, kernel_window_56_V_read, "(port)kernel_window_56_V_read");
    sc_trace(mVcdFile, kernel_window_57_V_read, "(port)kernel_window_57_V_read");
    sc_trace(mVcdFile, kernel_window_58_V_read, "(port)kernel_window_58_V_read");
    sc_trace(mVcdFile, kernel_window_59_V_read, "(port)kernel_window_59_V_read");
    sc_trace(mVcdFile, kernel_window_60_V_read, "(port)kernel_window_60_V_read");
    sc_trace(mVcdFile, kernel_window_61_V_read, "(port)kernel_window_61_V_read");
    sc_trace(mVcdFile, kernel_window_62_V_read, "(port)kernel_window_62_V_read");
    sc_trace(mVcdFile, kernel_window_63_V_read, "(port)kernel_window_63_V_read");
    sc_trace(mVcdFile, kernel_window_64_V_read, "(port)kernel_window_64_V_read");
    sc_trace(mVcdFile, kernel_window_65_V_read, "(port)kernel_window_65_V_read");
    sc_trace(mVcdFile, kernel_window_66_V_read, "(port)kernel_window_66_V_read");
    sc_trace(mVcdFile, kernel_window_67_V_read, "(port)kernel_window_67_V_read");
    sc_trace(mVcdFile, kernel_window_68_V_read, "(port)kernel_window_68_V_read");
    sc_trace(mVcdFile, kernel_window_69_V_read, "(port)kernel_window_69_V_read");
    sc_trace(mVcdFile, kernel_window_70_V_read, "(port)kernel_window_70_V_read");
    sc_trace(mVcdFile, kernel_window_71_V_read, "(port)kernel_window_71_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
    sc_trace(mVcdFile, ap_return_16, "(port)ap_return_16");
    sc_trace(mVcdFile, ap_return_17, "(port)ap_return_17");
    sc_trace(mVcdFile, ap_return_18, "(port)ap_return_18");
    sc_trace(mVcdFile, ap_return_19, "(port)ap_return_19");
    sc_trace(mVcdFile, ap_return_20, "(port)ap_return_20");
    sc_trace(mVcdFile, ap_return_21, "(port)ap_return_21");
    sc_trace(mVcdFile, ap_return_22, "(port)ap_return_22");
    sc_trace(mVcdFile, ap_return_23, "(port)ap_return_23");
    sc_trace(mVcdFile, ap_return_24, "(port)ap_return_24");
    sc_trace(mVcdFile, ap_return_25, "(port)ap_return_25");
    sc_trace(mVcdFile, ap_return_26, "(port)ap_return_26");
    sc_trace(mVcdFile, ap_return_27, "(port)ap_return_27");
    sc_trace(mVcdFile, ap_return_28, "(port)ap_return_28");
    sc_trace(mVcdFile, ap_return_29, "(port)ap_return_29");
    sc_trace(mVcdFile, ap_return_30, "(port)ap_return_30");
    sc_trace(mVcdFile, ap_return_31, "(port)ap_return_31");
    sc_trace(mVcdFile, ap_return_32, "(port)ap_return_32");
    sc_trace(mVcdFile, ap_return_33, "(port)ap_return_33");
    sc_trace(mVcdFile, ap_return_34, "(port)ap_return_34");
    sc_trace(mVcdFile, ap_return_35, "(port)ap_return_35");
    sc_trace(mVcdFile, ap_return_36, "(port)ap_return_36");
    sc_trace(mVcdFile, ap_return_37, "(port)ap_return_37");
    sc_trace(mVcdFile, ap_return_38, "(port)ap_return_38");
    sc_trace(mVcdFile, ap_return_39, "(port)ap_return_39");
    sc_trace(mVcdFile, ap_return_40, "(port)ap_return_40");
    sc_trace(mVcdFile, ap_return_41, "(port)ap_return_41");
    sc_trace(mVcdFile, ap_return_42, "(port)ap_return_42");
    sc_trace(mVcdFile, ap_return_43, "(port)ap_return_43");
    sc_trace(mVcdFile, ap_return_44, "(port)ap_return_44");
    sc_trace(mVcdFile, ap_return_45, "(port)ap_return_45");
    sc_trace(mVcdFile, ap_return_46, "(port)ap_return_46");
    sc_trace(mVcdFile, ap_return_47, "(port)ap_return_47");
    sc_trace(mVcdFile, ap_return_48, "(port)ap_return_48");
    sc_trace(mVcdFile, ap_return_49, "(port)ap_return_49");
    sc_trace(mVcdFile, ap_return_50, "(port)ap_return_50");
    sc_trace(mVcdFile, ap_return_51, "(port)ap_return_51");
    sc_trace(mVcdFile, ap_return_52, "(port)ap_return_52");
    sc_trace(mVcdFile, ap_return_53, "(port)ap_return_53");
    sc_trace(mVcdFile, ap_return_54, "(port)ap_return_54");
    sc_trace(mVcdFile, ap_return_55, "(port)ap_return_55");
    sc_trace(mVcdFile, ap_return_56, "(port)ap_return_56");
    sc_trace(mVcdFile, ap_return_57, "(port)ap_return_57");
    sc_trace(mVcdFile, ap_return_58, "(port)ap_return_58");
    sc_trace(mVcdFile, ap_return_59, "(port)ap_return_59");
    sc_trace(mVcdFile, ap_return_60, "(port)ap_return_60");
    sc_trace(mVcdFile, ap_return_61, "(port)ap_return_61");
    sc_trace(mVcdFile, ap_return_62, "(port)ap_return_62");
    sc_trace(mVcdFile, ap_return_63, "(port)ap_return_63");
    sc_trace(mVcdFile, ap_return_64, "(port)ap_return_64");
    sc_trace(mVcdFile, ap_return_65, "(port)ap_return_65");
    sc_trace(mVcdFile, ap_return_66, "(port)ap_return_66");
    sc_trace(mVcdFile, ap_return_67, "(port)ap_return_67");
    sc_trace(mVcdFile, ap_return_68, "(port)ap_return_68");
    sc_trace(mVcdFile, ap_return_69, "(port)ap_return_69");
    sc_trace(mVcdFile, ap_return_70, "(port)ap_return_70");
    sc_trace(mVcdFile, ap_return_71, "(port)ap_return_71");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_0_ce0, "line_buffer_Array_V_5_0_0_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_0_we0, "line_buffer_Array_V_5_0_0_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_0_q0, "line_buffer_Array_V_5_0_0_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_0_ce0, "line_buffer_Array_V_5_1_0_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_0_we0, "line_buffer_Array_V_5_1_0_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_0_q0, "line_buffer_Array_V_5_1_0_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_1_ce0, "line_buffer_Array_V_5_0_1_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_1_we0, "line_buffer_Array_V_5_0_1_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_1_q0, "line_buffer_Array_V_5_0_1_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_1_ce0, "line_buffer_Array_V_5_1_1_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_1_we0, "line_buffer_Array_V_5_1_1_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_1_q0, "line_buffer_Array_V_5_1_1_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_2_ce0, "line_buffer_Array_V_5_0_2_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_2_we0, "line_buffer_Array_V_5_0_2_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_2_q0, "line_buffer_Array_V_5_0_2_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_2_ce0, "line_buffer_Array_V_5_1_2_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_2_we0, "line_buffer_Array_V_5_1_2_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_2_q0, "line_buffer_Array_V_5_1_2_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_3_ce0, "line_buffer_Array_V_5_0_3_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_3_we0, "line_buffer_Array_V_5_0_3_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_3_q0, "line_buffer_Array_V_5_0_3_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_3_ce0, "line_buffer_Array_V_5_1_3_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_3_we0, "line_buffer_Array_V_5_1_3_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_3_q0, "line_buffer_Array_V_5_1_3_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_4_ce0, "line_buffer_Array_V_5_0_4_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_4_we0, "line_buffer_Array_V_5_0_4_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_4_q0, "line_buffer_Array_V_5_0_4_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_4_ce0, "line_buffer_Array_V_5_1_4_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_4_we0, "line_buffer_Array_V_5_1_4_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_4_q0, "line_buffer_Array_V_5_1_4_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_5_ce0, "line_buffer_Array_V_5_0_5_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_5_we0, "line_buffer_Array_V_5_0_5_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_5_q0, "line_buffer_Array_V_5_0_5_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_5_ce0, "line_buffer_Array_V_5_1_5_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_5_we0, "line_buffer_Array_V_5_1_5_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_5_q0, "line_buffer_Array_V_5_1_5_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_6_ce0, "line_buffer_Array_V_5_0_6_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_6_we0, "line_buffer_Array_V_5_0_6_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_6_q0, "line_buffer_Array_V_5_0_6_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_6_ce0, "line_buffer_Array_V_5_1_6_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_6_we0, "line_buffer_Array_V_5_1_6_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_6_q0, "line_buffer_Array_V_5_1_6_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_7_ce0, "line_buffer_Array_V_5_0_7_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_7_we0, "line_buffer_Array_V_5_0_7_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_0_7_q0, "line_buffer_Array_V_5_0_7_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_7_ce0, "line_buffer_Array_V_5_1_7_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_7_we0, "line_buffer_Array_V_5_1_7_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_5_1_7_q0, "line_buffer_Array_V_5_1_7_q0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

shift_line_buffer_array_ap_fixed_8u_config20_s::~shift_line_buffer_array_ap_fixed_8u_config20_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete line_buffer_Array_V_5_0_0_U;
    delete line_buffer_Array_V_5_1_0_U;
    delete line_buffer_Array_V_5_0_1_U;
    delete line_buffer_Array_V_5_1_1_U;
    delete line_buffer_Array_V_5_0_2_U;
    delete line_buffer_Array_V_5_1_2_U;
    delete line_buffer_Array_V_5_0_3_U;
    delete line_buffer_Array_V_5_1_3_U;
    delete line_buffer_Array_V_5_0_4_U;
    delete line_buffer_Array_V_5_1_4_U;
    delete line_buffer_Array_V_5_0_5_U;
    delete line_buffer_Array_V_5_1_5_U;
    delete line_buffer_Array_V_5_0_6_U;
    delete line_buffer_Array_V_5_1_6_U;
    delete line_buffer_Array_V_5_0_7_U;
    delete line_buffer_Array_V_5_1_7_U;
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv6_21;
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_0() {
    ap_return_0 = kernel_window_8_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_1() {
    ap_return_1 = kernel_window_9_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_10() {
    ap_return_10 = kernel_window_34_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_11() {
    ap_return_11 = kernel_window_35_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_12() {
    ap_return_12 = kernel_window_36_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_13() {
    ap_return_13 = kernel_window_37_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_14() {
    ap_return_14 = kernel_window_38_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_15() {
    ap_return_15 = kernel_window_39_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_16() {
    ap_return_16 = kernel_window_56_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_17() {
    ap_return_17 = kernel_window_57_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_18() {
    ap_return_18 = kernel_window_58_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_19() {
    ap_return_19 = kernel_window_59_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_2() {
    ap_return_2 = kernel_window_10_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_20() {
    ap_return_20 = kernel_window_60_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_21() {
    ap_return_21 = kernel_window_61_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_22() {
    ap_return_22 = kernel_window_62_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_23() {
    ap_return_23 = kernel_window_63_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_24() {
    ap_return_24 = kernel_window_16_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_25() {
    ap_return_25 = kernel_window_17_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_26() {
    ap_return_26 = kernel_window_18_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_27() {
    ap_return_27 = kernel_window_19_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_28() {
    ap_return_28 = kernel_window_20_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_29() {
    ap_return_29 = kernel_window_21_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_3() {
    ap_return_3 = kernel_window_11_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_30() {
    ap_return_30 = kernel_window_22_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_31() {
    ap_return_31 = kernel_window_23_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_32() {
    ap_return_32 = line_buffer_Array_V_5_1_0_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_33() {
    ap_return_33 = line_buffer_Array_V_5_1_1_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_34() {
    ap_return_34 = line_buffer_Array_V_5_1_2_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_35() {
    ap_return_35 = line_buffer_Array_V_5_1_3_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_36() {
    ap_return_36 = line_buffer_Array_V_5_1_4_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_37() {
    ap_return_37 = line_buffer_Array_V_5_1_5_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_38() {
    ap_return_38 = line_buffer_Array_V_5_1_6_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_39() {
    ap_return_39 = line_buffer_Array_V_5_1_7_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_4() {
    ap_return_4 = kernel_window_12_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_40() {
    ap_return_40 = kernel_window_40_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_41() {
    ap_return_41 = kernel_window_41_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_42() {
    ap_return_42 = kernel_window_42_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_43() {
    ap_return_43 = kernel_window_43_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_44() {
    ap_return_44 = kernel_window_44_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_45() {
    ap_return_45 = kernel_window_45_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_46() {
    ap_return_46 = kernel_window_46_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_47() {
    ap_return_47 = kernel_window_47_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_48() {
    ap_return_48 = line_buffer_Array_V_5_0_0_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_49() {
    ap_return_49 = line_buffer_Array_V_5_0_1_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_5() {
    ap_return_5 = kernel_window_13_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_50() {
    ap_return_50 = line_buffer_Array_V_5_0_2_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_51() {
    ap_return_51 = line_buffer_Array_V_5_0_3_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_52() {
    ap_return_52 = line_buffer_Array_V_5_0_4_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_53() {
    ap_return_53 = line_buffer_Array_V_5_0_5_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_54() {
    ap_return_54 = line_buffer_Array_V_5_0_6_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_55() {
    ap_return_55 = line_buffer_Array_V_5_0_7_q0.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_56() {
    ap_return_56 = kernel_window_64_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_57() {
    ap_return_57 = kernel_window_65_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_58() {
    ap_return_58 = kernel_window_66_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_59() {
    ap_return_59 = kernel_window_67_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_6() {
    ap_return_6 = kernel_window_14_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_60() {
    ap_return_60 = kernel_window_68_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_61() {
    ap_return_61 = kernel_window_69_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_62() {
    ap_return_62 = kernel_window_70_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_63() {
    ap_return_63 = kernel_window_71_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_64() {
    ap_return_64 = in_elem_data_0_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_65() {
    ap_return_65 = in_elem_data_1_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_66() {
    ap_return_66 = in_elem_data_2_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_67() {
    ap_return_67 = in_elem_data_3_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_68() {
    ap_return_68 = in_elem_data_4_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_69() {
    ap_return_69 = in_elem_data_5_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_7() {
    ap_return_7 = kernel_window_15_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_70() {
    ap_return_70 = in_elem_data_6_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_71() {
    ap_return_71 = in_elem_data_7_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_8() {
    ap_return_8 = kernel_window_32_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_return_9() {
    ap_return_9 = kernel_window_33_V_read.read();
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_0_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_0_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_0_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_0_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_1_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_1_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_1_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_1_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_2_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_2_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_2_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_2_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_2_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_3_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_3_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_3_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_3_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_3_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_4_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_4_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_4_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_4_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_4_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_5_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_5_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_5_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_5_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_5_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_6_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_6_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_6_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_6_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_6_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_6_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_7_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_7_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_7_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_0_7_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_0_7_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_0_7_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_0_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_0_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_0_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_0_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_1_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_1_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_1_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_1_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_2_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_2_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_2_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_2_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_2_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_3_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_3_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_3_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_3_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_3_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_4_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_4_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_4_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_4_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_4_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_5_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_5_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_5_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_5_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_5_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_6_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_6_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_6_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_6_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_6_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_6_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_7_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_7_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_7_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_line_buffer_Array_V_5_1_7_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        line_buffer_Array_V_5_1_7_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_5_1_7_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_fixed_8u_config20_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

