-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity shift_line_buffer_array_ap_fixed_8u_config20_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_elem_data_0_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    in_elem_data_1_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    in_elem_data_2_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    in_elem_data_3_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    in_elem_data_4_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    in_elem_data_5_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    in_elem_data_6_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    in_elem_data_7_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_8_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_9_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_10_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_11_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_12_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_13_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_14_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_15_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_16_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_17_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_18_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_19_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_20_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_21_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_22_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_23_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_32_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_33_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_34_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_35_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_36_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_37_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_38_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_39_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_40_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_41_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_42_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_43_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_44_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_45_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_46_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_47_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_56_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_57_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_58_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_59_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_60_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_61_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_62_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_63_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_64_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_65_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_66_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_67_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_68_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_69_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_70_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_window_71_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_45 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_46 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_47 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_48 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_49 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_50 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_51 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_52 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_53 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_54 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_55 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_56 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_57 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_58 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_59 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_60 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_61 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_62 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_63 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_64 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_65 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_66 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_67 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_68 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_69 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_70 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_71 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of shift_line_buffer_array_ap_fixed_8u_config20_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal line_buffer_Array_V_5_0_0_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_0_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_1_0_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_0_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_0_1_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_1_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_1_1_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_1_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_0_2_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_2_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_1_2_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_2_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_0_3_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_3_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_1_3_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_3_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_0_4_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_4_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_1_4_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_4_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_0_5_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_5_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_1_5_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_5_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_0_6_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_6_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_1_6_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_6_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_0_7_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_7_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_0_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_Array_V_5_1_7_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_7_we0 : STD_LOGIC;
    signal line_buffer_Array_V_5_1_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);

    component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    line_buffer_Array_V_5_0_0_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_0_0_ce0,
        we0 => line_buffer_Array_V_5_0_0_we0,
        d0 => in_elem_data_0_V_read,
        q0 => line_buffer_Array_V_5_0_0_q0);

    line_buffer_Array_V_5_1_0_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_1_0_ce0,
        we0 => line_buffer_Array_V_5_1_0_we0,
        d0 => line_buffer_Array_V_5_0_0_q0,
        q0 => line_buffer_Array_V_5_1_0_q0);

    line_buffer_Array_V_5_0_1_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_0_1_ce0,
        we0 => line_buffer_Array_V_5_0_1_we0,
        d0 => in_elem_data_1_V_read,
        q0 => line_buffer_Array_V_5_0_1_q0);

    line_buffer_Array_V_5_1_1_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_1_1_ce0,
        we0 => line_buffer_Array_V_5_1_1_we0,
        d0 => line_buffer_Array_V_5_0_1_q0,
        q0 => line_buffer_Array_V_5_1_1_q0);

    line_buffer_Array_V_5_0_2_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_0_2_ce0,
        we0 => line_buffer_Array_V_5_0_2_we0,
        d0 => in_elem_data_2_V_read,
        q0 => line_buffer_Array_V_5_0_2_q0);

    line_buffer_Array_V_5_1_2_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_1_2_ce0,
        we0 => line_buffer_Array_V_5_1_2_we0,
        d0 => line_buffer_Array_V_5_0_2_q0,
        q0 => line_buffer_Array_V_5_1_2_q0);

    line_buffer_Array_V_5_0_3_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_0_3_ce0,
        we0 => line_buffer_Array_V_5_0_3_we0,
        d0 => in_elem_data_3_V_read,
        q0 => line_buffer_Array_V_5_0_3_q0);

    line_buffer_Array_V_5_1_3_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_1_3_ce0,
        we0 => line_buffer_Array_V_5_1_3_we0,
        d0 => line_buffer_Array_V_5_0_3_q0,
        q0 => line_buffer_Array_V_5_1_3_q0);

    line_buffer_Array_V_5_0_4_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_0_4_ce0,
        we0 => line_buffer_Array_V_5_0_4_we0,
        d0 => in_elem_data_4_V_read,
        q0 => line_buffer_Array_V_5_0_4_q0);

    line_buffer_Array_V_5_1_4_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_1_4_ce0,
        we0 => line_buffer_Array_V_5_1_4_we0,
        d0 => line_buffer_Array_V_5_0_4_q0,
        q0 => line_buffer_Array_V_5_1_4_q0);

    line_buffer_Array_V_5_0_5_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_0_5_ce0,
        we0 => line_buffer_Array_V_5_0_5_we0,
        d0 => in_elem_data_5_V_read,
        q0 => line_buffer_Array_V_5_0_5_q0);

    line_buffer_Array_V_5_1_5_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_1_5_ce0,
        we0 => line_buffer_Array_V_5_1_5_we0,
        d0 => line_buffer_Array_V_5_0_5_q0,
        q0 => line_buffer_Array_V_5_1_5_q0);

    line_buffer_Array_V_5_0_6_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_0_6_ce0,
        we0 => line_buffer_Array_V_5_0_6_we0,
        d0 => in_elem_data_6_V_read,
        q0 => line_buffer_Array_V_5_0_6_q0);

    line_buffer_Array_V_5_1_6_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_1_6_ce0,
        we0 => line_buffer_Array_V_5_1_6_we0,
        d0 => line_buffer_Array_V_5_0_6_q0,
        q0 => line_buffer_Array_V_5_1_6_q0);

    line_buffer_Array_V_5_0_7_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_0_7_ce0,
        we0 => line_buffer_Array_V_5_0_7_we0,
        d0 => in_elem_data_7_V_read,
        q0 => line_buffer_Array_V_5_0_7_q0);

    line_buffer_Array_V_5_1_7_U : component shift_line_buffer_array_ap_fixed_1u_config2_s_line_bufferbkb
    generic map (
        DataWidth => 32,
        AddressRange => 34,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_21,
        ce0 => line_buffer_Array_V_5_1_7_ce0,
        we0 => line_buffer_Array_V_5_1_7_we0,
        d0 => line_buffer_Array_V_5_0_7_q0,
        q0 => line_buffer_Array_V_5_1_7_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= kernel_window_8_V_read;
    ap_return_1 <= kernel_window_9_V_read;
    ap_return_10 <= kernel_window_34_V_read;
    ap_return_11 <= kernel_window_35_V_read;
    ap_return_12 <= kernel_window_36_V_read;
    ap_return_13 <= kernel_window_37_V_read;
    ap_return_14 <= kernel_window_38_V_read;
    ap_return_15 <= kernel_window_39_V_read;
    ap_return_16 <= kernel_window_56_V_read;
    ap_return_17 <= kernel_window_57_V_read;
    ap_return_18 <= kernel_window_58_V_read;
    ap_return_19 <= kernel_window_59_V_read;
    ap_return_2 <= kernel_window_10_V_read;
    ap_return_20 <= kernel_window_60_V_read;
    ap_return_21 <= kernel_window_61_V_read;
    ap_return_22 <= kernel_window_62_V_read;
    ap_return_23 <= kernel_window_63_V_read;
    ap_return_24 <= kernel_window_16_V_read;
    ap_return_25 <= kernel_window_17_V_read;
    ap_return_26 <= kernel_window_18_V_read;
    ap_return_27 <= kernel_window_19_V_read;
    ap_return_28 <= kernel_window_20_V_read;
    ap_return_29 <= kernel_window_21_V_read;
    ap_return_3 <= kernel_window_11_V_read;
    ap_return_30 <= kernel_window_22_V_read;
    ap_return_31 <= kernel_window_23_V_read;
    ap_return_32 <= line_buffer_Array_V_5_1_0_q0;
    ap_return_33 <= line_buffer_Array_V_5_1_1_q0;
    ap_return_34 <= line_buffer_Array_V_5_1_2_q0;
    ap_return_35 <= line_buffer_Array_V_5_1_3_q0;
    ap_return_36 <= line_buffer_Array_V_5_1_4_q0;
    ap_return_37 <= line_buffer_Array_V_5_1_5_q0;
    ap_return_38 <= line_buffer_Array_V_5_1_6_q0;
    ap_return_39 <= line_buffer_Array_V_5_1_7_q0;
    ap_return_4 <= kernel_window_12_V_read;
    ap_return_40 <= kernel_window_40_V_read;
    ap_return_41 <= kernel_window_41_V_read;
    ap_return_42 <= kernel_window_42_V_read;
    ap_return_43 <= kernel_window_43_V_read;
    ap_return_44 <= kernel_window_44_V_read;
    ap_return_45 <= kernel_window_45_V_read;
    ap_return_46 <= kernel_window_46_V_read;
    ap_return_47 <= kernel_window_47_V_read;
    ap_return_48 <= line_buffer_Array_V_5_0_0_q0;
    ap_return_49 <= line_buffer_Array_V_5_0_1_q0;
    ap_return_5 <= kernel_window_13_V_read;
    ap_return_50 <= line_buffer_Array_V_5_0_2_q0;
    ap_return_51 <= line_buffer_Array_V_5_0_3_q0;
    ap_return_52 <= line_buffer_Array_V_5_0_4_q0;
    ap_return_53 <= line_buffer_Array_V_5_0_5_q0;
    ap_return_54 <= line_buffer_Array_V_5_0_6_q0;
    ap_return_55 <= line_buffer_Array_V_5_0_7_q0;
    ap_return_56 <= kernel_window_64_V_read;
    ap_return_57 <= kernel_window_65_V_read;
    ap_return_58 <= kernel_window_66_V_read;
    ap_return_59 <= kernel_window_67_V_read;
    ap_return_6 <= kernel_window_14_V_read;
    ap_return_60 <= kernel_window_68_V_read;
    ap_return_61 <= kernel_window_69_V_read;
    ap_return_62 <= kernel_window_70_V_read;
    ap_return_63 <= kernel_window_71_V_read;
    ap_return_64 <= in_elem_data_0_V_read;
    ap_return_65 <= in_elem_data_1_V_read;
    ap_return_66 <= in_elem_data_2_V_read;
    ap_return_67 <= in_elem_data_3_V_read;
    ap_return_68 <= in_elem_data_4_V_read;
    ap_return_69 <= in_elem_data_5_V_read;
    ap_return_7 <= kernel_window_15_V_read;
    ap_return_70 <= in_elem_data_6_V_read;
    ap_return_71 <= in_elem_data_7_V_read;
    ap_return_8 <= kernel_window_32_V_read;
    ap_return_9 <= kernel_window_33_V_read;

    line_buffer_Array_V_5_0_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_0_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_0_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_0_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_1_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_1_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_2_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_2_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_2_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_2_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_3_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_3_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_3_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_3_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_4_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_4_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_4_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_4_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_5_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_5_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_5_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_5_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_6_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_6_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_6_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_6_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_7_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_7_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_0_7_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_0_7_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_0_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_0_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_0_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_0_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_1_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_1_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_2_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_2_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_2_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_2_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_3_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_3_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_3_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_3_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_4_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_4_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_4_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_4_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_5_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_5_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_5_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_5_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_6_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_6_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_6_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_6_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_7_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_7_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_5_1_7_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            line_buffer_Array_V_5_1_7_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_5_1_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
